### PR TITLE
Feature: add opt-in "unitlessPrecision" flag for line heights

### PR DESCRIPTION
**Pull request by flo-sch**
- feat(tokens): add unitlessPrecision config for lineHeights
  - opt-in config flag allowing to set the decimals precision (defaults to 2: current hardcoded value)
  - improve parseCliArgs function (preserve arguments sorting order)
  - add unit-test cases for new config flag
  - mention how to override in README.md
- fix(types): refactor parseCliArgs with typed setConfigValue
- refactor: attempt to reduce SonarCloud warnings
  - try to reduce duplicate implementations in parseCliArgs
  - immediate return of lineHeightTokens reduce result

### CODE REVIEW

**Comment by flo-sch** [comment]
I missed that one so far but I have a need to customize that precision in some cases (to more than 2 decimals)

**Comment by flo-sch** [comment]
Reduced CS from 15 to 3, others are on other parts I did not really touch ;)

**Comment by mikaelvesavuori** [comment]
Thanks! Merging

**Comment by flo-sch** [comment]
Great :)
Can you keep me in touch when you release a new patch?

**Pull request merged**
